### ISSUE TITLE
Autotools build broken?

### ISSUE THREAD

**Issue by essen** [massemanet/eper#40]
Last commit removed file README which is required by automake. The following change fixes it:

``` patch
diff --git a/configure.ac b/configure.ac
index ad3ca39..4d16afb 100644
--- a/configure.ac
+++ b/configure.ac
@@ -10,7 +10,7 @@ AC_COPYRIGHT(Copyright (C) 2008-2013 Mats Cronqvist)
 dnl AC_REVISION($Id$)
 
 dnl Require automake version >=1.9.5.
-AM_INIT_AUTOMAKE(1.9.5)
+AM_INIT_AUTOMAKE([foreign], 1.9.5)
 
 dnl Erlang-related configuration.
 AC_ERLANG_SUBST_ROOT_DIR
```

However that's not all. Running make after that results in beam files created in src/, no .app file and so on.

Does anyone actually use the autotools build? Shouldn't it just be removed? I can do that if that's OK.

**Comment by massemanet** [comment]
the README was renamed README.md... ooops.
there is no .app file, because eper was not (initially) an application.
the .beam files gets moved to the right place when you run make install.
the whole autotools rigamarole was added by some guy who wented to package eper into .deb/.rpm . I have no idea if that was ever used, or if it still is.

**Comment by massemanet** [comment]
fixed (?) in 8e9eee4

**Comment by essen** [comment]
Have to go, will get back to you when I get back.

**Comment by essen** [comment]
Right this fixes the first issue but this doesn't produce a valid OTP application like the normal Makefile does.

Should it be fixed? In my case I would be perfectly fine without the autotools stuff, they're only used here because they are available and some applications do use them (ejabberd, exmpp and a few others) so when configure.ac is available we try this first.

I could do an exception for this application (rm configure.ac basically) but if nobody use the autotools stuff (not seeing the package in Debian or elsewhere; seeing a non-official Fedora one that uses rebar to compile (https://filabrazilska.fedorapeople.org/erlang-eper.spec)) then perhaps it's best to just remove them?

I can send a patch if you give me the OK. I love removing things.

**Comment by massemanet** [comment]
I'll most likely take such a patch :)

**Comment by essen** [comment]
OK then. It's already late here so I will do that tomorrow.

**Comment by essen** [comment]
Sent in #41.

**Comment by sata** [comment]
Any update? :)

**Comment by massemanet** [comment]
testing as de speak

**Comment by massemanet** [comment]
releases in 0.93

**Comment by sata** [comment]
Awesome! Thanks so much

**Comment by essen** [comment]
Cheers, seems to be working, thanks!
