### ISSUE TITLE
Erlang 21 compat

### ISSUE THREAD

**Issue by GalaxyGorilla** [massemanet/eper#57]
When I try to compile eper with erlang 21 I just get
```
 % ./rebar3 compile
===> Verifying dependencies...
===> Compiling eper
===> Compiling src/redbug.erl failed
```
which is not exactly a helpful error message :P.

I fiddled a little bit around, removed the stacktrace statements and some other stuff which might be incompatible with erlang 21. Also I removed the ?log macros which look like a dark art anyway, but all this did not change anything. Any idea what's going on here?

**Comment by GalaxyGorilla** [comment]
OK, this is because of `warnings_as_errors` in the `rebar.config`. Thanks to @michalwski who mentioned the issue in esl/MongooseIM#1947! Weirdly I don't even get any warning printed on my machine :(.

**Comment by massemanet** [comment]
trying to work around this with evil hacks in ```rebar.config.script```

**Comment by massemanet** [comment]
vsn 0.99.1 of eper should be OTP21 clean
